### ISSUE TITLE
Teste de Issues

### ISSUE THREAD

**Issue by luizluvizutto** [natorsc/databases-with-python#1]
Fala fera! To testando a coisa aqui... Abraço!!

**Comment by natorsc** [comment]
Fala mestre, manda ver nos teste e se precisar de ajuda ou encontrar algum erro estou a disposição.

Se tudo correr bem amanha devo subir um repositório com alguns exemplo de programação web com Python e Django.

É que postei um pouco sobre o ORM do Django no [LinkedIn](https://www.linkedin.com/pulse/django-orm-cookbook-renato-dos-santos-cruz/) e a galera curtiu.

Amanhã vou atualizar o post do LinkedIn e adicionar uma versão em slide para download que fiz no [SlideShare](https://www.slideshare.net/natorsc/django-orm-cookbook).
